server:
  port: 8085
spring:
  r2dbc:
    url: r2dbc:pool:postgres://localhost:5432/task_api_db
    username: postgres
    password: root
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    url: jdbc:postgresql://localhost:5432/task_api_db
    locations: classpath:db/migration
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  application:
    name: TASK-API-MAIN
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    db: jdbc:postgresql://localhost:5432/security?serverTimezone=UTC
    userInfoPath: http://localhost:8765/security/v1/users/info

