spring:
  application:
    name: mail-notification
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
server:
  port: 8087
application:
  security:
    jwt:
      secret-email-verification-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration-email-key: 3600000 # an hour
  link-to-verify: http://localhost:8765/request-handler/v1/email
  link-to-accept-invitation-to-project: http://localhost:8765/request-handler/v1/email

