spring:
  config:
    import: optional:classpath:application-secrets.yaml
  application:
    name: mail-notification
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5432/notification_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    url: jdbc:postgresql://localhost:5432/notification_db
    locations: classpath:db/migration
    user: postgres
    password: root
#  quartz:
#    config: classpath:quartz.properties
#logging:
#  level:
#    org:
#      quartz: INFO  # Уровень логирования Quartz
#    root: INFO
server:
  port: 8086
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
application:
  security:
    jwt:
      secret-email-verification-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration-email-key: 3600000 # an hour
  link-to-verify: http://localhost:8765/request-handler/v1/email
  link-to-accept-invitation-to-project: http://localhost:8765/request-handler/v1/email
  telegram-bot:
    url-to-send: http://localhost:8087/tg-bot/v1
