spring:
  application:
    name: SECURITY
  datasource:
    url: jdbc:postgresql://localhost:5432/security?serverTimezone=UTC
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
  mail:
    properties:
      mail:
        transport:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
            ssl:
              enable: true
          protocol: smtp
    host: smtp.yandex.ru
    port: 465
    username: matveygrom2017@yandex.ru
    password: psajdfm43
  liquibase:
    change-log: classpath:liquibase/db.changelog-master.xml
    url: jdbc:postgresql://localhost:5432/security?serverTimezone=UTC
    user: postgres
    password: root
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 9898
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      secret-email-verification-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5971
      expiration: 3600000 # an hour
      refresh-token:
        expiration: 604800000 # 7 days
  task-api:
    db-url: jdbc:postgresql://localhost:5432/task_api_db?serverTimezone=UTC
